# Generated by Django 5.2.13 on 2026-04-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
