# Generated by Django 5.2.13 on 2026-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_priority_ticket_resolution_ticket_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='evolution_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='evolution_api_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
