# Generated by Django 5.2.14 on 2026-05-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_company_evolution_api_key_company_evolution_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
