# Generated by Django 5.2.14 on 2026-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
