# Generated by Django 5.2.14 on 2026-05-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_unread_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp', 'id']},
        ),
    ]
