# Generated by Django 5.2.14 on 2026-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_unread_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_agency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='carrier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='consumidor_final',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato Principal'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_name2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_opinion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='due_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_commercial',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail Comercial'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_financial',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail Financeiro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='customer',
            name='foundation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fundação'),
        ),
        migrations.AddField(
            model_name='customer',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='customer',
            name='municipal_inscription',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nao_contribuinte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='obs_financial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='obs_invoice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='optante_simples',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='representative_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_inscription',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Razão Social / Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Telefone Principal'),
        ),
    ]
