# Generated by Django 5.2.14 on 2026-05-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_customer_bank_account_customer_bank_agency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp', 'id']},
        ),
    ]
