# Generated by Django 5.2.14 on 2026-06-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_message_edited_at_message_is_edited_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='quoted_message_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='quoted_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='quoted_message_sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
