# Generated by Django 5.2.14 on 2026-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_absenceschedule_quickreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
