# Generated by Django 5.2.14 on 2026-06-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_contact_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('ibge_code', models.CharField(max_length=7, unique=True, verbose_name='Código IBGE')),
            ],
            options={
                'ordering': ['name', 'state'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='city_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tickets.city', verbose_name='Cidade (Vínculo)'),
        ),
    ]
