# Generated by Django 5.2.14 on 2026-07-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_city_customer_city_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('pending', 'Pendente'), ('closed', 'Finalizada')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=20)),
                ('operation_type', models.CharField(choices=[('suporte', 'Suporte'), ('desenvolvimento', 'Desenvolvimento'), ('consultoria', 'Consultoria / Assessoria'), ('atualizacao', 'Atualização'), ('reuniao', 'Reunião'), ('tef', 'TEF'), ('reforma_tributaria', 'Reforma Tributária')], default='suporte', max_length=50)),
                ('opening_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencies', to='tickets.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencies', to='tickets.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencies', to='tickets.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pendencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='PendencyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pendency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tickets.pendency')),
            ],
        ),
    ]
