# Generated by Django 5.2.16 on 2026-07-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_user_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pendency_report_only_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='pendency_report_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
