# Generated by Django 5.2.16 on 2026-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_contact_birth_date_contact_cellphone_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendency',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('closed', 'Finalizada')], default='open', max_length=20),
        ),
    ]
