# Generated by Django 5.2.16 on 2026-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_webcalfeed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['ticket', 'timestamp'], name='tickets_mes_ticket__810624_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', 'status'], name='tickets_tic_company_0e5f54_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', 'updated_at'], name='tickets_tic_company_a1e5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['contact', 'status'], name='tickets_tic_contact_5c7d7b_idx'),
        ),
    ]
