# Generated by Django 5.2.17 on 2026-08-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_user_avatar'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'remote_jid'], name='tickets_con_company_3146f2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['customer', 'phone'], name='tickets_con_custome_14e5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', '-updated_at'], name='tickets_con_company_9b29db_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'name'], name='tickets_cus_company_f06369_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'is_blocked'], name='tickets_cus_company_72d726_idx'),
        ),
        migrations.AddIndex(
            model_name='pendency',
            index=models.Index(fields=['company', 'status'], name='tickets_pen_company_7c73db_idx'),
        ),
        migrations.AddIndex(
            model_name='pendency',
            index=models.Index(fields=['customer', 'status'], name='tickets_pen_custome_35fc67_idx'),
        ),
        migrations.AddIndex(
            model_name='pendency',
            index=models.Index(fields=['user', 'status'], name='tickets_pen_user_id_584529_idx'),
        ),
        migrations.AddIndex(
            model_name='pendency',
            index=models.Index(fields=['company', '-created_at'], name='tickets_pen_company_198e2d_idx'),
        ),
    ]
