# Generated by Django 5.2.17 on 2026-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_contact_tickets_con_company_3146f2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_company_a1e5b3_idx',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'phone'], name='tickets_con_company_68cd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'whatsapp'], name='tickets_con_company_f54f09_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['ticket', '-timestamp'], name='tickets_mes_ticket__41fab9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', 'status', '-updated_at'], name='tickets_tic_company_c4258d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', '-updated_at'], name='tickets_tic_company_5f1668_idx'),
        ),
    ]
