# Generated by Django 5.2.17 on 2026-09-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_ticketreminder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketreminder',
            new_name='tickets_tic_is_sent_50dd71_idx',
            old_name='tickets_tic_is_sent_c653a1_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketreminder',
            new_name='tickets_tic_ticket__ec17cc_idx',
            old_name='tickets_tic_ticket__3e9112_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketreminder',
            new_name='tickets_tic_company_f60b8a_idx',
            old_name='tickets_tic_company_07f3b8_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketreminder',
            new_name='tickets_tic_user_id_a8a270_idx',
            old_name='tickets_tic_user_id_45a190_idx',
        ),
    ]
